### ISSUE TITLE
Re-rooting to a scaled down pod can sometimes reset crew-capacity

### ISSUE THREAD

**Issue by numberlesstim** [JonnyOThan/TweakScale#32]
Steps to reproduce: 

1. Attach 2 pods ontop of each other using the match node feature
2. Copy the smaller pod (hold alt + click) and re-attach to the top, again using the match node feature 3 or 4 times
3. Re-root to the smallest pod
4. (Optional) Remove all but the root pod
5. You should now have a tiny pod with the default crew capacity

(lower pod in image is the default size for scale)
![capacity](https://github.com/JonnyOThan/TweakScale/assets/117858473/ce0d1ae2-7e1f-4d1f-9b07-0c95afb62b0f)

**Comment by numberlesstim** [comment]
I can still reproduce this bug in the latest version (v3.1.3).

**Comment by JonnyOThan** [comment]
Same repro steps?

**Comment by numberlesstim** [comment]
Yes.

https://github.com/JonnyOThan/TweakScale/assets/117858473/e7b0c1a3-8fe8-45e0-b5d9-0672a90cc0e6

**Comment by JonnyOThan** [comment]
Ah, so my previous fix only worked when the partManifest for the scaled down part still existed in the vesselCrewManifest.  But something about this flow is resulting in the partManifest for the root part not being there.  You can hit the same UpdateCrewForVessel call if you scale down a command pod so that it has no crew, then attach a fuel tank, then delete the tank.  But the partManifest exists in that case and everything works.  Why doesn't it exist after re-rooting?

**Comment by numberlesstim** [comment]
This can also be done with a subassembly in place of a single pod with the same steps you provided.
